extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - plugin:prettier/recommended
  - prettier
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - prettier
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: ./
root: true
rules:
  prettier/prettier: error
