service: serverless-http-api-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  handler:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-plugin-typescript