service: i-say-hello
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: lambda-deploy-artifacts

functions:
  handler:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-esbuild
  - serverless-offline
