service: i-say-hello
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  # deploymentBucket:
  #   name: lambda-deploy-artifacts-3355e9ebda0
  environment:
    STAGE: ${opt:stage, 'dev'}

functions:
  handler:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-esbuild
  - serverless-offline
