AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    typescript-monolithic-express

Globals:
    Function:
        Timeout: 3

Resources:
    ExpressFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: index.handler
            Runtime: nodejs20.x
            Architectures:
                - x86_64
            Events:
                ExpressRoot:
                    Type: Api
                    Properties:
                        Path: '/'
                        Method: ANY
                Express:
                    Type: Api
                    Properties:
                        Path: '/{proxy+}'
                        Method: ANY
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - index.ts

Outputs:
    ExpressApi:
        Description: 'API Gateway endpoint URL for Prod stage for Express function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{proxy+}'
    ExpressFunction:
        Description: 'Express Lambda Function ARN'
        Value: !GetAtt ExpressFunction.Arn
    ExpressFunctionIamRole:
        Description: 'Implicit IAM Role created for Express function'
        Value: !GetAtt ExpressFunctionRole.Arn
